/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhosRouteImport } from './routes/trabalhos'
import { Route as RiscosProcedimentosRouteImport } from './routes/riscos-procedimentos'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PapeisTrabalhoRouteImport } from './routes/papeis-trabalho'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentosEvidenciasRouteImport } from './routes/documentos-evidencias'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AcessoPendenteRouteImport } from './routes/acesso-pendente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const TrabalhosRoute = TrabalhosRouteImport.update({
  id: '/trabalhos',
  path: '/trabalhos',
  getParentRoute: () => rootRouteImport,
} as any)
const RiscosProcedimentosRoute = RiscosProcedimentosRouteImport.update({
  id: '/riscos-procedimentos',
  path: '/riscos-procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PapeisTrabalhoRoute = PapeisTrabalhoRouteImport.update({
  id: '/papeis-trabalho',
  path: '/papeis-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosEvidenciasRoute = DocumentosEvidenciasRouteImport.update({
  id: '/documentos-evidencias',
  path: '/documentos-evidencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoPendenteRoute = AcessoPendenteRouteImport.update({
  id: '/acesso-pendente',
  path: '/acesso-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos-evidencias': typeof DocumentosEvidenciasRoute
  '/login': typeof LoginRoute
  '/papeis-trabalho': typeof PapeisTrabalhoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao': typeof RevisaoRoute
  '/riscos-procedimentos': typeof RiscosProcedimentosRoute
  '/trabalhos': typeof TrabalhosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos-evidencias': typeof DocumentosEvidenciasRoute
  '/login': typeof LoginRoute
  '/papeis-trabalho': typeof PapeisTrabalhoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao': typeof RevisaoRoute
  '/riscos-procedimentos': typeof RiscosProcedimentosRoute
  '/trabalhos': typeof TrabalhosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-pendente': typeof AcessoPendenteRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos-evidencias': typeof DocumentosEvidenciasRoute
  '/login': typeof LoginRoute
  '/papeis-trabalho': typeof PapeisTrabalhoRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao': typeof RevisaoRoute
  '/riscos-procedimentos': typeof RiscosProcedimentosRoute
  '/trabalhos': typeof TrabalhosRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-pendente'
    | '/clientes'
    | '/configuracoes'
    | '/documentos-evidencias'
    | '/login'
    | '/papeis-trabalho'
    | '/planejamento'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/revisao'
    | '/riscos-procedimentos'
    | '/trabalhos'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-pendente'
    | '/clientes'
    | '/configuracoes'
    | '/documentos-evidencias'
    | '/login'
    | '/papeis-trabalho'
    | '/planejamento'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/revisao'
    | '/riscos-procedimentos'
    | '/trabalhos'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/acesso-pendente'
    | '/clientes'
    | '/configuracoes'
    | '/documentos-evidencias'
    | '/login'
    | '/papeis-trabalho'
    | '/planejamento'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/revisao'
    | '/riscos-procedimentos'
    | '/trabalhos'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoPendenteRoute: typeof AcessoPendenteRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentosEvidenciasRoute: typeof DocumentosEvidenciasRoute
  LoginRoute: typeof LoginRoute
  PapeisTrabalhoRoute: typeof PapeisTrabalhoRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RevisaoRoute: typeof RevisaoRoute
  RiscosProcedimentosRoute: typeof RiscosProcedimentosRoute
  TrabalhosRoute: typeof TrabalhosRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhos': {
      id: '/trabalhos'
      path: '/trabalhos'
      fullPath: '/trabalhos'
      preLoaderRoute: typeof TrabalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riscos-procedimentos': {
      id: '/riscos-procedimentos'
      path: '/riscos-procedimentos'
      fullPath: '/riscos-procedimentos'
      preLoaderRoute: typeof RiscosProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papeis-trabalho': {
      id: '/papeis-trabalho'
      path: '/papeis-trabalho'
      fullPath: '/papeis-trabalho'
      preLoaderRoute: typeof PapeisTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos-evidencias': {
      id: '/documentos-evidencias'
      path: '/documentos-evidencias'
      fullPath: '/documentos-evidencias'
      preLoaderRoute: typeof DocumentosEvidenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-pendente': {
      id: '/acesso-pendente'
      path: '/acesso-pendente'
      fullPath: '/acesso-pendente'
      preLoaderRoute: typeof AcessoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoPendenteRoute: AcessoPendenteRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentosEvidenciasRoute: DocumentosEvidenciasRoute,
  LoginRoute: LoginRoute,
  PapeisTrabalhoRoute: PapeisTrabalhoRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  RevisaoRoute: RevisaoRoute,
  RiscosProcedimentosRoute: RiscosProcedimentosRoute,
  TrabalhosRoute: TrabalhosRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
